spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ENC(8JkUC4DM1PPxL707TY93kSw0nIO45stSSkhP0rD9qvcy8uY285QQpxlJQMJu+l8qA00Z0IZ0HFVhxHGVLoRTxtlkQd3Htja/8/3kwUo2fkEL+lvhVMurj/FJdjQBrwmT)
    username: ENC(UqLApY5ox+wtETTgrpb7WCncGkfDARN0)
    password: ENC(zrw+5JxSAGgSoGML6qeVZ1jfyOWlMa60)
    driver-class-name: com.mysql.cj.jdbc.Driver

cloud:
  aws:
    s3:
      bucket: clonecodingairbb
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ENC(Sb6y8B4R2KE1o2S4p704B0Wmm0W4E8X3K6zmz2P+QoE=)
      secretKey: ENC(KnaWa0nSwld2HpIwRg7p6ccAYqadaB7629PD8BxdQ6z5eFrIS7Y17agWNiroQ+Z9dN0LFJB+nLk=)
